### ISSUE TITLE
Can’t change role value on a notification banner

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/govuk-components#109]
I’m looking to use the new notification component, and show a success message after a user has successful completed a task. The design system, [says this](https://design-system.service.gov.uk/components/notification-banner/#reacting-to-something-the-user-has-done):

> Since you’re using the notification banner to tell the user about the outcome of something they’ve just done, add `role="alert"` so focus shifts to the notification banner on page load.

However, as far as I can tell, this value is hard coded to `region`: https://github.com/DFE-Digital/govuk-components/blob/e963f4749572f6ae8668adcc64b3db24e6f92f50/app/components/govuk_component/notification_banner.html.erb#L1

Have I understood this correctly? Does this advice also not conflict somewhat with the `disable_auto_focus` option? (I’m not sure if `role="alert"` should always mean attracting focus on page load, but this seems reasonable).

**Comment by peteryates** [comment]
D'oh, this is a bug purely caused by the poor ordering of the arguments in that `tag.div` call.

Once #110 has been released you'll be able to set the role via the `html_attributes`, so something like:

```ruby
render GovukComponent::NotificationBanner.new(title: "omg", html_attributes: { role: "marquee" })
```

**Comment by paulrobertlloyd** [comment]
Once again, amazing turnaround! A++++, will file bugs again 😉 Thanks @peteryates!
