### ISSUE TITLE
Update notification banner to be flexible in what it accepts

### ISSUE THREAD

**Issue by fofr** [DFE-Digital/govuk-components#119]
The notification banner could include a variety of content. The API for this component should be as flexible as the design system's.

The following is not currently possible:

```html
You are impersonating <a href="/">Paul Hayes</a> (email@email.com)

[Stop impersonating]
```

Suggestion:
- Add an `html` param, to pass in and render any provided html

Like:

```
{{ govukNotificationBanner({
  html: html
}) }}
```

https://design-system.service.gov.uk/components/notification-banner/

This is affecting this PR: https://github.com/DFE-Digital/get-help-with-tech/pull/1410

**Comment by peteryates** [comment]
I think you should be able to do this now by passing in your content [with a block](https://github.com/DFE-Digital/govuk-components/blob/master/app/components/govuk_component/notification_banner.html.erb#L21):

```
<%= govuk_notification_banner(blah) do %>
  <h2>Inner content goes here</h2>
<% end %>
```

**Comment by fofr** [comment]
Ah, nice. Is there an example of this usage in the docs?

**Comment by peteryates** [comment]
Yeah, there is. Admittedly the docs on this project could do with a bit of a reorganisation, I'd like to get them laid out similarly to the form builder's at some point. It's quite an involved task though!

![Screenshot from 2021-03-10 16-12-06](https://user-images.githubusercontent.com/128088/110664248-238b4b00-81bf-11eb-9df7-bea645d036ca.png)

**Comment by peteryates** [comment]
Ah! To be honest I think I added the `render?` method before thinking about allowing arbitrary content via blocks. I'll just remove it, can totally see why it's a pain in the rear 😅
