### ISSUE TITLE
Add option for collapsing breadcrumbs on mobile devices

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/govuk-components#125]
See: https://design-system.service.gov.uk/components/breadcrumbs/#collapsing-breadcrumbs-on-mobile-devices

**Comment by frankieroberto** [comment]
@paulrobertlloyd could you already do this by passing in a class, maybe?

```ruby
render GovukComponent::Breadcrumbs.new(breadcrumbs: {
  'Level one': '/level-one/',
  'Level two': '/level-one/level-two/',
  'Level three': '/level-one/level-two/level-three'
}, classes: "govuk-breadcrumbs--collapse-on-mobile")
```

**Comment by paulrobertlloyd** [comment]
Yup, just a question of making it a more explicit option (like it is in the Nunjucks macro)

**Comment by frankieroberto** [comment]
Ah yes, +1 for that! I was also unsure from the documentation/code whether you need to also include `govuk-breadcrumbs` when passing in classes, or whether they just add additional classes (like the Nunjucks version)?
