### ISSUE TITLE
Add cookie banner to component preview page

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/govuk-components#128]
https://dfe-digital.github.io/govuk-components/ doesn’t feature a preview or documentation for the recently added cookie banner component.

**Comment by peteryates** [comment]
Ah yeah, looks like there's a preview but the design system version's out of date so it's not properly-styled.

**Comment by paulrobertlloyd** [comment]
Okay, this is embarrassing… turns out nothing was appearing for me because I have an overly zealous blocker… so it’s impressive you still found a bug here! 😅
