### ISSUE TITLE
Header: No menu button added to reveal navigation items on mobile

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/govuk-components#132]
If you add items to the header, the following markup should be added after `.govuk-header__link` and prior to the `nav` element:

```html
<button type="button" class="govuk-header__menu-button govuk-js-header-toggle" aria-controls="navigation" aria-label="Show or hide navigation menu">Menu</button>
```

This allows the navigation to be revealed in the mobile breakpoint.

Furthermore, as there’s no way to insert content within the header, this button markup can’t be added manually.

See: https://design-system.service.gov.uk/components/header/#header-with-service-name-and-navigation

**Comment by paulrobertlloyd** [comment]
Also worth nothing that the design system allows the default text for this button to be overridden via `menuButtonLabel`.

**Comment by paulrobertlloyd** [comment]
Was there anything preventing this issue being addressed in the last round of fixes?

**Comment by peteryates** [comment]
Other than me forgetting to do it, nope. They'll be at the top of the next batch!

**Comment by paulrobertlloyd** [comment]
No worries… I think I’ve found another feature request relating to the header anyway! 😉
