### ISSUE TITLE
Header: No ability to set product name

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/govuk-components#133]
The header component can take a product name - the regular weight text which can appear right after the GOV.UK logo. We use this variant on Apply. See: https://github.com/DFE-Digital/apply-for-teacher-training/blob/master/app/components/product_header_component.html.erb

(Additionally, we also include a tag after the product name. This option is not available in the design systems Nunjucks templates, but sure would be nice to have a means of injecting custom content into product name area should this be desired)

**Comment by peteryates** [comment]
Fixed by #138
