### ISSUE TITLE
Start now button: Incorrect name?

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/govuk-components#137]
Now this is _really_ pernickety, but… what’s called the ‘Start now button’ component in this gem, is commonly referred to as the ‘Start button’. See: https://design-system.service.gov.uk/components/button/#start-buttons (Also, the class is `govuk-button--start`).

Suppose it’s too late to rename this component… or at least until there’s a breaking change?

**Comment by frankieroberto** [comment]
Arguably it could be an option passed to the `govuk_link_to` or `govuk_button_to` helpers instead? Or we create a new `Button` component...

Trade-offs between more closely following the `govuk-frontend` macros vs the Rails conventions...!

**Comment by peteryates** [comment]
I did a quick GitHub search to see if the component was in use anywhere and there are a few - I'll hold off the renaming until the next major version and leave this issue as a reminder.

**Comment by frankieroberto** [comment]
In _theory_ we shouldn't be using the Start now button in services, as it should only be on GOV.UK start pages... ;-)
