### ISSUE TITLE
Allow setting visually hidden text for change links in summary lists

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/govuk-components#165]
Typically, the ‘Change’ link in a summary list is composed of 2 parts: the visible link (usually labelled ‘Change’), and a visually hidden part, which helps tell change links apart when a screen reader announces them.

Currently, the `action` param for a row in `GovukComponent::SummaryList` is pretty dumb; it’ll take anything. However, given this link pattern is so intrinsic to this component, it’d be much more helpful if this component enabled setting these values.

How about, in addition to taking any value as it does currently:

```HTML+ERB
<%= component.slot(
    :row,
    key: 'Name',
    value: 'Aardvark',
    action: link_to('Change', '#aardvark')
) %>
```

you can supply an object with the following values instead:

```HTML+ERB
<%= component.slot(
    :row,
    key: 'Name',
    value: 'Aardvark',
    action: {
        href: "#aardvark",             # Required
        text: "Change",                # Required, defaults to ‘Change’ if not provided 
        visually_hidden_text: "name",  # Required, but maybe defaults to lowercased `key` value? 
        classes: "",                   # Optional
        html_attributes: {},           # Optional
    }
) %>
```

Something like that.

**Comment by peteryates** [comment]
Excellent suggestion, totally on board with it.
