### ISSUE TITLE
ViewComponent `with_slot` is deprecated

### ISSUE THREAD

**Issue by BroiSatse** [DFE-Digital/govuk-components#173]
```
DEPRECATION WARNING: `with_slot` is deprecated and will be removed in ViewComponent v3.0.0.
Use the new slots API (https://viewcomponent.org/guide/slots.html) instead.
```

https://github.com/github/view_component/releases/tag/v2.31.0

**Comment by peteryates** [comment]
We're in the process of upgrading, the latest version of ViewComponent will be fully supported and warning-free in [version 2.0.0](#158).
