### ISSUE TITLE
Allow string or block content where Nunjucks templates allow both text or html values 

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/govuk-components#182]
Feature request for v2. Just seen that the param for the details component has been renamed to `summary_text`, to match that of the GDS Design system nunjucks template, `summaryText`. This is perfect, but it has reminded me…

A number of params in the design system templates are sort of paired, and the details element is a good example. For this component, you can supply both the summary and disclosed text values with plain text strings:

```njk
{{ govukDetails({
  summaryText: "See some details",
  text: "Is this what you expected?"
}) }}
```

However, you can also provide HTML to both of these values:

```njk
{{ govukDetails({
  summaryHtml: "See some <strong>important<strong> details",
  html: "<p class="\govuk-body\">Getta load of <em>these</em> details!</p>"
}) }}
```

For all the places these param pairs exist in the Nunjucks templates, this gem should behave similarly, either excepting a string or a block. (Currently the details component accepts block content only for the disclosed text, but not the summary text).

**Comment by paulrobertlloyd** [comment]
(Block, or maybe a slot…? Unsure on the specifics!)

**Comment by peteryates** [comment]
So the `DetailsComponent` takes a block and will favour it over `text` if both are supplied.

You should be able to do:

```erb
<%= govuk_details(summary_text: "Extra extra") %>
  <marquee>Read all about it</marquee>
<% end %>
```

If it's not working as expected I'll dig a little.

**Comment by paulrobertlloyd** [comment]
That’s for `text`, I’m talking about `summary_text` (and other similar instances in the different components).

**Comment by peteryates** [comment]
Oh yeah I see what you mean now. Yeah, that's a good call.

**Comment by peteryates** [comment]
Had a quick stab at it, #188 

We can re-use this pattern quite easily to allow anything to be overridden with HTML.

**Comment by peteryates** [comment]
@paulrobertlloyd if you spot any other instances where this approach would make sense please let me know and I'll add them too.
