### ISSUE TITLE
`govuk_link_to` misbehaves when given url_options without any html_options.

### ISSUE THREAD

**Issue by BroiSatse** [DFE-Digital/govuk-components#193]
When `govuk_link_to` is called with url_options hash (https://apidock.com/rails/ActionView/Helpers/UrlHelper/link_to) it appends class to url_options instead of html_options, resulting in link without `govuk-link` class and with href with appended `?class=govuk-link`.

```
    <%= govuk_link_to "show", action: :show %>  #=> <a href="{correct_url}?class=govuk-link">
```
This can be avoided by adding `button: false` and parenthesising url_options:

```
    <%= govuk_link_to "show", { action: :show }, button: false %>  #=> <a class="govuk-link" href="{correct_url}">
```

Parenthesising alone does not fix the issue - url_options are then still treated as kwargs rather than part of *args (which I find a bit odd - this might depend on ruby version though)

**Comment by peteryates** [comment]
Thanks for reporting, this looks somewhat related to #66 - something we didn't come up with a solution for. Rails' super-flexible implementation makes adding a class and passing everything else on to `#link_to` quite a headache.

I'll have a closer look and try to get this resolved in the upcoming v2 release. Suggestions or PRs welcome.

**Comment by peteryates** [comment]
I've had a look at this and a couple of attempts at fixing it gets really ugly, especially with the [differences in how Ruby 2.7.x and 3.0.0 handle hashes, braces and kwargs]. I don't think there's a clean solution.

I wonder if providing a helper that returns an array of classes and leaving it for developers to use it in combination with `link_to` is going to be a more sensible approach.

```ruby
link_to("show", { action: show }, { class: govuk_link_classes(muted: true, inverse: true) })
```

Despite being a bit wordier it would have the advantage of working with the whole `link_to` family (`link_to_if`, `link_to_unless`, `link_to_unless_current`, etc).

I'm going to create something along those lines in a branch and see how it looks.

**Comment by peteryates** [comment]
Going to close this now, I believe this is now working properly in the v2 branch. Please reopen if it's not!
