### ISSUE TITLE
Parity with the Nunjucks macros

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/govuk-components#202]
@paulrobertlloyd has created a comprehensive list of differences between this library and the Nunjucks macros that are provided by the [Design System](https://design-system.service.gov.uk/components/).

Most of them fall into the categories of renaming arguments to match or adding slots to match the `html:` behaviour from Nunjucks. The most important ones will be included in version 2.0.0.

| Component               | GDS Design System        | GOV.UK Components          | Recommended change                                                                                                                                                               |
| ---------------------   | ------------------------ | -------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| ✔️   ~~**Accordion**~~ #203           | `attributes`             | `html_attributes`          |                                                                                                                                                                                  |
|                         | `classes`                | `classes`                  |                                                                                                                                                                                  ||
|                         | `id`                     | `id`                       |                                                                                                                                                                                  |
|                         | `headingLevel`           | **MISSING**                | Add `heading_level` param, defaults to `2`                                                                                                                                           |
|                         | `items`                  | `sections`                 |                                                                                                                                                                                  |
|                         | ↳ `heading.text`         | ↳ `title`                  | Rename `heading_text`                                                                                                                                                              |
|                         | ↳ `heading.html`         | ↳ **MISSING**              | Add `heading_html` slot                                                                                                                                                            |
|                         | ↳ `su mmary.text`         | ↳ `summary`                | Rename `summary_text`                                                                                                                                                              |
|                         | ↳ `summary.html`         | ↳ **MISSING**              | Add `summary_html` slot                                                                                                                                                            |
|                         | ↳ `content.text`         | ↳ **MISSING**              | Add `text` param                                                                                                                                                                   |
|                         | ↳ `content.html`         | ↳ content                  |                                                                                                                                                                                  |
|                         | ↳ `expanded`             | ↳ `expanded`               |                                                                                                                                                                                  |
| ✔️  ~~**Back link**~~ #207            | `attributes`             | `html_attributes`          |                                                                                                                                                                                  |
|                         | `classes`                | `classes`                  |                                                                                                                                                                                  |
|                         | `text`                   | `text`                     |                                                                                                                                                                                  |
|                         | `html`                   | **MISSING**                | Accept content block                                                                                                                                                             |
|                         | `href`                   | `href`                     |                                                                                                                                                                                  |
| ✔️  ~~**Breadcrumbs**~~ #211          | `attributes`             | `html_attributes`          |                                                                                                                                                                                  |
|                         | `classes`                | `classes`                  |                                                                                                                                                                                  |
|                         | `collapseOnMobile`       | `collapse_on_mobile`       |                                                                                                                                                                                  |
|                         | **MISSING**              | `hide_in_print`            |                                                                                                                                                                                  |
|                         | `items`                  | `breadcrumbs`              |                                                                                                                                                                                  |
|                         | ↳ `text`                 | ↳ `text`                   |                                                                                                                                                                                  |
|                         | ↳ `html`                 | **MISSING**                |                                                                                                                                                                                  |
|                         | ↳ `href`                 | ↳ `link`                   | Rename `href`                                                                                                                                                                      |
|                         | ↳ `attributes`           | **MISSING**                |                                                                                                                                                                                  |
|                         |                          | ↳ `present`                |                                                                                                                                                                                  |
| ✔️  ~~**Cookie banner**~~ #223        | `attributes`             | `html_attributes`          |                                                                                                                                                                                  |
|                         | `classes`                | `classes`                  |                                                                                                                                                                                  |
|                         | `ariaLabel`              | `aria_label`               |                                                                                                                                                                                  |
|                         | `hidden`                 | `html_attributes.hidden`   | Add `hidden` param                                                                                                                                                                 |
|                         |                          | `role`                     | Remove, and determine based on type                                                                                                                                              |
|                         | `messages`               | **MISSING**                | Replace `body` with `message` slot. This would allow the component to take multiple messages which prevent having to render the component multiple times, as is the case on Apply.   |
|                         | ↳ `attributes`           |                            |                                                                                                                                                                                  |
|                         | ↳ `classes`              |                            |                                                                                                                                                                                  |
|                         | ↳ `headingText`          |                            |                                                                                                                                                                                  |
|                         | ↳ `headingHtml`          |                            |                                                                                                                                                                                  |
|                         | ↳ `text`                 |                            |                                                                                                                                                                                  |
|                         | ↳ `html`                 |                            |                                                                                                                                                                                  |
|                         | ↳ `hidden`               |                            |                                                                                                                                                                                  |
|                         | ↳ `role`                 |                            |                                                                                                                                                                                  |
|                         | ↳ `actions`              | `actions`                  |                                                                                                                                                                                  |
|                         | ↳ `attributes`           | **MISSING**                | Documentation suggests providing an array of `link` helpers, but should this be more structured? You could concievably provide an array of anything into actions right now.        |
|                         | ↳ `classes`              |                            |                                                                                                                                                                                  |
|                         | ↳ `text`                 |                            |                                                                                                                                                                                  |
|                         | ↳ `type`                 |                            |                                                                                                                                                                                  |
|                         | ↳ `href`                 |                            |                                                                                                                                                                                  |
|                         | ↳ `name`                 |                            |                                                                                                                                                                                  |
|                         | ↳ `value`                |                            |                                                                                                                                                                                  |
| ✔️  ~~**Details**~~ #214              | `attributes`             | `html_attributes`          |                                                                                                                                                                                  |
|                         | `classes`                | `classes`                  |                                                                                                                                                                                  |
|                         | `id`                     | `html_attributes.id`       | Add `id` param                                                                                                                                                                     |
|                         | `open`                   | `html_attributes.open`     | Add `open` param                                                                                                                                                                   |
|                         | `summaryText`            | `summary_text`             |                                                                                                                                                                                  |
|                         | `summaryHtml`            | `summary_html`             |                                                                                                                                                                                  |
|                         | `text`                   | `text`                     |                                                                                                                                                                                  |
|                         | `html`                   | `content`                  |                                                                                                                                                                                  |
| ✔️  ~~**Footer**~~ #209               | `attributes`             | `html_attributes`          |                                                                                                                                                                                  |
|                         | `classes`                | `classes`                  |                                                                                                                                                                                  |
|                         | `containerClasses`       | **MISSING**                | Add `container_classes` param                                                                                                                                                      |
|                         | **MISSING**              | `copyright_text`           |                                                                                                                                                                                  |
|                         | **MISSING**              | `copyright_url`            |                                                                                                                                                                                  |
|                         | **MISSING**              | `meta_licence`             |                                                                                                                                                                                  |
|                         | `meta`                   | `meta`                     |                                                                                                                                                                                  |
|                         | ↳ `visuallyHiddenTitle`  | `meta_items_title`         |                                                                                                                                                                                  |
|                         | ↳ `text`                 | **MISSING**                | Add `meta_text` param                                                                                                                                                              |
|                         | ↳ `html`                 | `meta_content`             | Rename `meta_html`                                                                                                                                                                 |
|                         | ↳ `items`                | `meta_items`               |                                                                                                                                                                                  |
|                         | ↳ `text`                 | ↳ `text`                   |                                                                                                                                                                                  |
|                         | ↳ `html`                 | **MISSING**                |                                                                                                                                                                                  |
|                         | ↳ `href`                 | ↳ `href`                   |                                                                                                                                                                                  |
|                         | ↳ `attributes`           | **MISSING**                |                                                                                                                                                                                  |
|                         | `navigation`             | **MISSING**                | I’d be tempted to continue ignoring this, as use case served by allowing custom meta content.                                                                                    |
|                         | ↳ `title`                |                            |                                                                                                                                                                                  |
|                         | ↳ `columns`              |                            |                                                                                                                                                                                  |
|                         | ↳ `items`                |                            |                                                                                                                                                                                  |
|                         | ↳ `text`                 |                            |                                                                                                                                                                                  |
|                         | ↳ `html`                 |                            |                                                                                                                                                                                  |
|                         | ↳ `attributes`           |                            |                                                                                                                                                                                  |
| ✔️  ~~**Header**~~ #212              | `attributes`             | `html_attributes`          |                                                                                                                                                                                  |
|                         | `classes`                | `classes`                  |                                                                                                                                                                                  |
|                         | `containerClasses`       | `container_classes`        |                                                                                                                                                                                  |
|                         | `homepageUrl`            | `homepage_url`             |                                                                                                                                                                                  |
|                         | `productName`            | `product_name`             |                                                                                                                                                                                  |
|                         | `serviceName`            | `service_name`             |                                                                                                                                                                                  |
|                         | `serviceUrl`             | `service_url`              |                                                                                                                                                                                  |
|                         | `menuButtonLabel`        | `menu_button_label`        |                                                                                                                                                                                  |
|                         | `navigationClasses`      | `navigation_classes`       |                                                                                                                                                                                  |
|                         | `navigationLabel`        | `navigation_label`         |                                                                                                                                                                                  |
|                         | `navigation`             | `items`                    | Rename `navigation`                                                                                                                                                                |
|                         | ↳ `text`                 | ↳ `text`                   |                                                                                                                                                                                  |
|                         | ↳ `html`                 | ↳ `html`                   |                                                                                                                                                                                  |
|                         | ↳ `href`                 | ↳ `href`                   |                                                                                                                                                                                  |
|                         | ↳ `active`               | ↳ `active`                 |                                                                                                                                                                                  |
|                         | ↳ `attributes`           | ↳ `html_attributes`        |                                                                                                                                                                                  |
|                         | **MISSING**              | ↳ `classes`                |                                                                                                                                                                                  |
|                         | **MISSING**              | `logotype`                 |                                                                                                                                                                                  |
|                         | **MISSING**              | `crown`                    |                                                                                                                                                                                  |
| ✔️  ~~**Inset text**~~ #208           | `attributes`             | `html_attributes`          |                                                                                                                                                                                  |
|                         | `classes`                | `classes`                  |                                                                                                                                                                                  |
|                         | `id`                     | `html_attributes.id`       | Add `id` param                                                                                                                                                                     |
|                         | `text`                   | `text`                     |                                                                                                                                                                                  |
|                         | `html`                   | `content`                  |                                                                                                                                                                                  |
| ✔️  ~~**Notification banner**~~ #213  | `attributes`             | `html_attributes`          |                                                                                                                                                                                  |
|                         | `classes`                | `classes`                  |                                                                                                                                                                                  |
|                         | **MISSING**              | `headings`                 |                                                                                                                                                                                  |
|                         | `text`                   | **MISSING**                | Add `text` param                                                                                                                                                                   |
|                         | `html`                   | `content`                  |                                                                                                                                                                                  |
|                         | `titleText`              | `title`                    | Rename `title_text`                                                                                                                                                                |
|                         | `titleHtml`              | **MISSING**                | Add `title_html` slot                                                                                                                                                              |
|                         | `titleHeadingLevel`      | `title_heading_level`      |                                                                                                                                                                                  |
|                         | `titleId`                | `title_id`                 |                                                                                                                                                                                  |
|                         | `type`                   | **MISSING**                | Takes either `success` or `nil`                                                                                                                                                      |
|                         | `role`                   | `html_attributes.role`     | Add role param                                                                                                                                                                   |
|                         | `disableAutoFocus`       | `disable_auto_focus`       |                                                                                                                                                                                  |
| ✔️  ~~**Panel**~~ #215                | `attributes`             | `html_attributes`          |                                                                                                                                                                                  |
|                         | `classes`                | `classes`                  |                                                                                                                                                                                  |
|                         | `id`                     | `html_attributes.id`       | Add `id` param                                                                                                                                                                     |
|                         | `headingLevel`           | **MISSING**                | Add `heading_level` param, defaults to `1`                                                                                                                                           |
|                         | `text`                   | `body`                     | Rename `text`                                                                                                                                                                      |
|                         | `html`                   | `content`                  |                                                                                                                                                                                  |
|                         | `titleText`              | `title`                    | Rename `title_text`                                                                                                                                                                |
|                         | `titleHtml`              | **MISSING**                | Add `title_html` slot                                                                                                                                                              |
| ✔️  ~~**Phase banner**~~ #205        | `attributes`             | `html_attributes`          |                                                                                                                                                                                  |
|                         | `classes`                | `classes`                  |                                                                                                                                                                                  |
|                         | `text`                   | `text`                     |                                                                                                                                                                                  |
|                         | `html`                   | `content`                  |                                                                                                                                                                                  |
|                         | `tag`                    | `phase_tag`                | Rename `tag`                                                                                                                                                                        |
| ✔️  ~~**Skip link**~~ #206             | `attributes`             | `html_attributes`          |                                                                                                                                                                                  |
|                         | `classes`                | **MISSING**                |                                                                                                                                                                                  |
|                         | `text`                   | `text`                     |                                                                                                                                                                                  |
|                         | `html`                   | **MISSING**                | Accept content block                                                                                                                                                             |
|                         | `href`                   | `href`                     |                                                                                                                                                                                  |
| ✔️  ~~**Start button**~~ (no action needed)        | N/A                      | `html_attributes`          |                                                                                                                                                                                  |
|                         | N/A                      | `classes`                  |                                                                                                                                                                                  |
|                         | N/A                      | `text`                     |                                                                                                                                                                                  |
|                         | N/A                      | `html`                     |                                                                                                                                                                                  |
|                         | N/A                      | `href`                     |                                                                                                                                                                                  |
| ✔️  ~~**Summary list**~~ #222         | `attributes`             | `html_attributes`          |                                                                                                                                                                                  |
|                         | `classes`                | `classes`                  |                                                                                                                                                                                  |
|                         | `rows`                   | `rows`                     |                                                                                                                                                                                  |
|                         | ↳ `key.text`             | ↳ `key`                    | Rename `key_text`                                                                                                                                                                  |
|                         | ↳ `key.html`             | ↳ **MISSING**              | Add `key_html` slot                                                                                                                                                                |
|                         | ↳ `key.classes`          | ↳ **MISSING**              | Add `classes` param                                                                                                                                                                |
|                         | ↳ `value.text`           | ↳ `value`                  | Rename `value_text`                                                                                                                                                                |
|                         | ↳ `value.html`           | ↳ **MISSING**              | Add `value_html` slot                                                                                                                                                              |
|                         | ↳ `value.classes`        | ↳ **MISSING**              | Add `classes` param                                                                                                                                                                |
|                         | ↳ `actions.classes`      | ↳ **MISSING**              | Add `classes` param                                                                                                                                                                |
|                         | ↳ `actions.items`        | ↳ `actions`                |                                                                                                                                                                                  |
|                         | ↳ `href`                 | ↳ `href`                   |                                                                                                                                                                                  |
|                         | ↳ `text`                 | ↳ `text`                   |                                                                                                                                                                                  |
|                         | ↳ `html`                 | ↳ **MISSING**              | Accept `content` block                                                                                                                                                             |
|                         | ↳ `visuallyHiddenText`   | ↳ `visually_hidden_text`   |                                                                                                                                                                                  |
|                         | ↳ `attributes`           | ↳ `html_attributes`        |                                                                                                                                                                                  |
|                         | ↳ `classes`              | ↳ `classes`                |                                                                                                                                                                                  |
| ✔️  ~~**Tabs**~~ #220                | `attributes`             | `html_attributes`          |                                                                                                                                                                                  |
|                         | `classes`                | `classes`                  |                                                                                                                                                                                  |
|                         | `id`                     | `html_attributes.id`       | Add `id` param                                                                                                                                                                     |
|                         | `idPrefix`               | **MISSING**                | `prefix` appears in code but not initializer                                                                                                                                       |
|                         | `title`                  | `title`                    |                                                                                                                                                                                  |
|                         | `items`                  | `tabs`                     |                                                                                                                                                                                  |
|                         | ↳ `id`                   | ↳ **MISSING**              |                                                                                                                                                                                  |
|                         | ↳ `label`                | ↳ `title`                  | Rename `label`                                                                                                                                                                     |
|                         | ↳ `attributes`           | ↳ **MISSING**              |                                                                                                                                                                                  |
|                         | ↳ `panel.text`           | ↳ **MISSING**              | Add `text` param                                                                                                                                                                   |
|                         | ↳ `panel.html`           | ↳ `content`                |                                                                                                                                                                                  |
|                         | ↳ `panel.attributes`     | ↳ `html_attributes`        |                                                                                                                                                                                  |
|                         | **MISSING**              | ↳ `classes`                |                                                                                                                                                                                  |
| ✔️   ~~**Tag**~~ #204               | `attributes`             | `html_attributes`          |                                                                                                                                                                                  |
|                         | `classes`                | `classes`                  |                                                                                                                                                                                  |
|                         | `text`                   | `text`                     |                                                                                                                                                                                  |
|                         | `html`                   | **MISSING**                | Accept `content` block                                                                                                                                                             |
|                         | **MISSING**              | `colour`                   |                                                                                                                                                                                  |
| ✔️ ~~**Warning text**~~ #221         | `attributes`             | `html_attributes`          |                                                                                                                                                                                  |
|                         | `classes`                | `classes`                  |                                                                                                   _assistive                                                                               |
|                         | `iconFallbackText`       | `assistive_text`           | Rename `icon_fallback_text`                                                                                                                                                        |
|                         | `text`                   | `text`                     |                                                                                                                                                                                  |
|                         | `html`                   | `content`                  |

**Comment by paulrobertlloyd** [comment]
The notification banner component needs to follow the same means of enabling the success variant: this gem currently uses `success: true`, when really it should be `type: 'success'`.

**Comment by peteryates** [comment]
I had a look at this and in the guidance it says:

> You can use only the `"success"` or `null` values with this option.

This is setting a boolean value via a string, which I think is more complicated than it needs to be. Until there are more types I think sticking with the flag makes more sense.

**Comment by paulrobertlloyd** [comment]
> Until there are more types I think sticking with the flag makes more sense.

Good point, fair enough.
