### ISSUE TITLE
Gotcha: Use of non-strings in block-form slots

### ISSUE THREAD

**Issue by csutter** [DFE-Digital/govuk-components#249]
The `view_component` gem uses [`ActionView::Helpers::CaptureHelper#capture`](https://github.com/rails/rails/blob/main/actionview/lib/action_view/helpers/capture_helper.rb#L46) internally to capture HTML content from a block. This will silently (and perhaps unexpectedly) discard any non-string values.

This causes the following possibly unexpected behaviour:

```erb
<%= govuk_summary_list do |summary_list| %>
  <% summary_list.row do |row| %>
    <% row.key { "OK: Renders '123'" } %>
    <% row.value(text: 123) %>
  <% end %>
  <% summary_list.row do |row| %>
    <% row.key { "OK: Renders '123'" } %>
    <% row.value { "123" } %>
  <% end %>
  <% summary_list.row do |row| %>
    <% row.key { "OK: Renders '123'" } %>
    <% row.value do %>
      123
    <% end %>
  <% end %>
  <% summary_list.row do |row| %>
    <% row.key { "FAIL: Renders nothing" } %>
    <% row.value { 123 } %>
  <% end %>
<% end %>
```

This is intended behaviour from ActionView (as `#capture` is only meant to deal with content coming from a templating library like ERB, which are guaranteed to be strings, not blocks returning arbitrary values). `view_component` has decided _not_ to work around it: https://github.com/github/view_component/pull/849

Having talked through it amongst ourselves at TV, our consensus in the team now is to only use the block form of passing content into components/slots when we're actually capturing template code, not when passing values in.

One of the examples for `SummaryListComponent` demonstrates the use of the block form to pass in plain strings: https://github.com/DFE-Digital/govuk-components/blob/master/spec/dummy/app/views/demos/examples/_summary_list.html.erb#L8 - the fact that this works is coincidental, as this happens to be passing in strings, but it wouldn't work for any other kind of value (which isn't obvious at all).

Would it be useful to a) change these examples, and/or b) point out this gotcha in the `govuk-components` docs (if so, where would be best)?

**Comment by peteryates** [comment]
Yeah - thanks for raising this. I've come across it recently too and it's an annoyance - in a perfect world we wouldn't require a certain working knowledge of Rails' innards to make sense of it.

I think the main issue is that we're restricted to writing Ruby in the documentation examples whereas in reality most components will be used from templates where this would work:

```erb
<%= govuk_panel(title_text: "Winning number:") do %>
  <%= 123 %>
<% end %>
```

I'm currently exploring rewriting the docs (#244) using ViewComponent's built-in preview functionality (via [LookBook](https://github.com/allmarkedup/lookbook/)) so it'd make sense to address this problem there. I've added a task to remove and replace occurrences.

**Comment by peteryates** [comment]
@csutter - I believe the [new guide](https://github.com/github/view_component/issues/1128) solves this by [using Slim for the example snippets](https://github.com/DFE-Digital/govuk-components/blob/main/guide/lib/examples/header_helpers.rb#L9).

I'll also look at adding a paragraph on the topic on the [Using components](https://govuk-components.netlify.app/introduction/using-components/) page.
