### ISSUE TITLE
Reference to fallback crown image is hardcoded

### ISSUE THREAD

**Issue by frankieroberto** [DFE-Digital/govuk-components#256]
The header component contains a fallback `<img>` tag, for when a browser doesn’t support inline SVG.

The `src` of the tag [is hardcoded](https://github.com/DFE-Digital/govuk-components/blob/master/app/components/govuk_component/header_component.html.erb#L12) to `/assets/images/govuk-logotype-crown.png`.

However there is no guarantee that the image will be available at this URL, depending on how the asset pipeline, etc is set up – and the image URL currently 404s on many of our service, for example:

* https://www.apply-for-teacher-training.service.gov.uk/assets/images/govuk-logotype-crown.png
* https://www.find-postgraduate-teacher-training.service.gov.uk/assets/images/govuk-logotype-crown.png
* https://www.register-trainee-teachers.education.gov.uk/assets/images/govuk-logotype-crown.png

As a short-term fix, we could replace the hardcode url with a param, and update our services so that they pass in a path to that image?

**Comment by peteryates** [comment]
Yeah, that sounds like a good solution to me. I guess the longer term fix would be to allow these things to be set via config, but having a path override will make sense either way.

**Comment by frankieroberto** [comment]
Yeah, the trickier problem is somehow getting services to remember to do this, as it'd require a bit of manual work to copy the right file to the right folder and then figure out how to reference it (depending on how webpacker, etc is set up). I think I'd be tempted to put it in the `/public` folder and skip the asset pipeline completely.

If the path isn't specified, should we not include the image at all, or raise an exception to force it to be specified (would be a breaking change)?

**Comment by peteryates** [comment]
Fixed in #257
