### ISSUE TITLE
Add summary list component

### ISSUE THREAD

**Issue by rjlynch** [DFE-Digital/govuk-components#26]
[Design system](https://design-system.service.gov.uk/components/summary-list/)    
[Nunjucks implementation](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/summary-list/template.njk)

**Comment by rjlynch** [comment]
Coming up with a good api for this component will take some thinking.
The nunjucks api for this allows a lot of configuration but makes the common/simple case of key/value/change link quite verbose.

**Comment by peteryates** [comment]
I had a crack at this (#48). As far as I can see the easiest way to keep the API simple is to use the Slot API and let the dev pass in whatever they like for the `action:`. Here's an example:

```ruby
render GovukComponent::SummaryList.new do |component|
  component.slot(
    :row,
    key: 'Aardvark',
    value: 'The aardvark is vaguely pig-like in appearance',
    action: link_to('Change', href: '#aardvark')
  )
end
```
