### ISSUE TITLE
Rename `master` branch as `main`

### ISSUE THREAD

**Issue by cpjmcquillan** [DFE-Digital/govuk-components#265]
Rename `master` branch as `main`.

There is no doubt the term `master` can have negative connotations 
and implications. This means it has the capacity to cause offence and 
do harm to others. 

This is something that's relatively straightforward to do. There is 
useful [documentation][1] and an informative [repository][2] so I
advocate this is something we should do sooner rather than later.

If there is agreement, I am happy to pick this up.

[1]: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch 
[2]: https://github.com/github/renaming

**Comment by paulrobertlloyd** [comment]
@peteryates Can we do this for `v3.0.0`?

**Comment by peteryates** [comment]
Yeah good call, will do the same on form builder too

**Comment by peteryates** [comment]
Done 🎉
