### ISSUE TITLE
Section break helper

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/govuk-components#321]
:wave: Long time, no feature request!

There are currently no helpers for typography. Arguably this can/should remain the concern of a different gem (such as [GOV.UK Markdown renderer](https://github.com/dfE-Digital/govuk_markdown)).

However, it’s not unusual for [section breaks](https://design-system.service.gov.uk/styles/typography/#section-break) to be used in layouts, outside of content. My advice to colleagues regarding building services using this gem is “if you’re writing HTML, you probably shouldn’t be”. Using HTML for section breaks goes against that advice.

## Proposal

Rather than write this HTML

```html
<hr class="govuk-section-break govuk-section-break--visible govuk-section-break--m">
```

provide a helper with options consistent with those used elsewhere:

```erb
<%= govuk_section_break %> =>
<hr class="govuk-section-break">

<%= govuk_section_break(visible: true) %> =>
<hr class="govuk-section-break govuk-section-break--visible">

<%= govuk_section_break(visible: true, size: "m") %> =>
<hr class="govuk-section-break govuk-section-break--visible govuk-section-break--m">

<%= govuk_section_break(visible: true, size: "s") %> =>
[This would throw an error as small section breaks are not a thing, weirdly]
```

**Comment by cpjmcquillan** [comment]
This sounds sensible to me, and I'm happy to implement it.

@peteryates what do you think?

**Comment by peteryates** [comment]
Yeah, good call @paulrobertlloyd - I suspect they're implemented by just about every service going.

Amazing, thanks @cpjmcquillan!

**Comment by peteryates** [comment]
Might be of interest but I experimented a bit with some other [layout-related components](https://github.com/DFE-Digital/govuk-components/pull/52/files) a while ago. In the columns example there's a bit of extra complexity but there are a few things that could be made easier just with a helper, like rows, headings, lists.

Could be an interesting follow up to this work.

**Comment by paulrobertlloyd** [comment]
Seeing as this issue is still open…

Tried upgrading to 3.0.5 but got an error:

`expected file /home/runner/work/submit-social-housing-lettings-and-sales-data/submit-social-housing-lettings-and-sales-data/vendor/bundle/ruby/3.1.0/gems/govuk-components-3.0.5/app/components/govuk_component/traits/custom_classes.rb to define constant GovukComponent::Traits::CustomClasses, but didn't`

Tests pass locally, but not when running tests on GitHub actions. Might this be an issue with this gem now pulling in `html-attributes-utils` and what that expects?

**Comment by peteryates** [comment]
Thanks @paulrobertlloyd - my fault I left a file in that should've been deleted. #331 will fix it and there'll be a fix out this morning.

**Comment by peteryates** [comment]
I _think_ we should be all good here now. Please re-open if something isn't quite right!

**Comment by paulrobertlloyd** [comment]
Brill, all working now. Thanks so much @peteryates and @cpjmcquillan 🙏
