### ISSUE TITLE
Accordion with javascript disabled

### ISSUE THREAD

**Issue by gpeng** [DFE-Digital/govuk-components#322]
We've come across some strange sub-heading styling on the accordion component when javascript is disabled:

<img width="739" alt="Screenshot 2022-05-27 at 15 21 45" src="https://user-images.githubusercontent.com/5216/170720364-cea5bf4e-7f7c-4cd5-8162-50273d95282b.png">

The design system has no background on the headings:

<img width="889" alt="Screenshot 2022-05-27 at 15 28 00" src="https://user-images.githubusercontent.com/5216/170720565-ae6504cd-2cd0-4333-83d2-9bb8355bc8b8.png">

**Comment by peteryates** [comment]
Interesting.

On [the accordion guide page](https://govuk-components.netlify.app/components/accordion/) with JavaScript disabled I get no grey box around the header:

![Screenshot from 2022-05-27 16-59-47](https://user-images.githubusercontent.com/128088/170736429-9923c55a-f230-42f0-8ee7-4dde1221ba97.png)


Which version of `govuk-frontend` are you running?

**Comment by peteryates** [comment]
Closing this for now, happy to reopen if it's definitely a form builder bug but I think it's either down to an older version of `govuk-frontend` or a local style.
