### ISSUE TITLE
Loading `CustomClasses` module error

### ISSUE THREAD

**Issue by cwrw** [DFE-Digital/govuk-components#330]
The latest version release `3.0.5` Integrates the `html_attributes_utils` gem. However after the following change: https://github.com/DFE-Digital/govuk-components/pull/323/files#diff-47916f9bed4926158567a03abbcbc68fea84954b4277aca066a9bb02382f82aaL3 we aren't able to load Rails due to the following error:
```
Zeitwerk::NameError
expected file /usr/local/bundle/gems/govuk-components-3.0.5/app/components/govuk_component/traits/custom_classes.rb to define constant GovukComponent::Traits::CustomClasses, but didn't
```

**Comment by peteryates** [comment]
Ah thanks @cwrw. I thought I'd removed the file entirely. Will get a fix out shortly.
