### ISSUE TITLE
Allow custom attributes for meta links in footer

### ISSUE THREAD

**Issue by rhysbarrett** [DFE-Digital/govuk-components#348]
One of our requirements is that our meta links must open in a new tab. For this to work we need to be able to add the following custom attributes to each meta (footer) link: `target: '_blank', rel: 'noopener noreferrer'`.

These attributes appear to be accepted by the implementation but not actually applied:

![Screenshot 2022-07-06 at 17 27 47](https://user-images.githubusercontent.com/43062389/177598751-bcf451a7-63d2-40a7-b47a-930f7a0bd79b.png)

Is it possible to honour these custom attributes?

**Comment by peteryates** [comment]
Thanks @rhysbarrett - this was an oversight on my part. The `custom_meta_html_attributes` are applied to the meta container not each item. I've raised a PR (#349) that adds support for an array of hashes (in addition to the current hash) which should give you what you need.

**Comment by peteryates** [comment]
Fixed by #349
