### ISSUE TITLE
Idea: add `scope` parameter to CellComponent

### ISSUE THREAD

**Issue by naseberry** [DFE-Digital/govuk-components#377]
`<th>` scope attribute.

The `scope` attribute specifies whether a header cell is a header for a column, row, or group of columns or rows `<th scope="col|row|colgroup|rowgroup">`.
The `scope` attribute has no visual effect in web browsers, but can be used by screen readers.

The [design system](https://design-system.service.gov.uk/components/table/) header cell should:

- have `scope="col"` when nested within `<thead>`
- have `scope="row"` when nested within `<tbody>`

At present, we can pass `scope` as an html attribute `html_attributes: { scope: "" }`, however it could be better to include the design system default attributes where possible, thereby making the call simpler, for example `scope: ""`

**Comment by peteryates** [comment]
This sounds like a good move to me. It's really straightforward to do in the mode where we pass in an array but a bit trickier to do when building the table 'DSL-style' as I'm not entirely sure how to deduce which component the slot belongs to. It might be doable using [lambda slots](https://viewcomponent.org/guide/slots.html#lambda-slots), I'll take a closer look. Thanks!
