### ISSUE TITLE
Accordion section IDs should be derived using the component ID rather than headings

### ISSUE THREAD

**Issue by edwardhorsford** [DFE-Digital/govuk-components#409]
See related conversation on [cross gov slack](https://ukgovernmentdigital.slack.com/archives/C6DMEH5R6/p1679416057509069).

The accordion component seems to [derive the section IDs](https://github.com/DFE-Digital/govuk-components/blob/main/app/components/govuk_component/accordion_component/section_component.rb#L18) using the heading for the section. This is different than how the design system does it, where they are [derived using the component id and an incrementing count](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/accordion/template.njk#L18).

## Description of bug
Unfortunately this causes a bug with the javascript of the accordion that attempts to preserve the open status of individual sections. The bug will mean that unrelated accordions will end up sharing their section open status.

The javascript attempts to keep preserve open status of sections across page loads. The docs for the component suggest this is done using the ID of the component. Teams are meant to give accordions unique IDs (across the domain, not the page), and the js will use this to persistently save the open status. Under the hood, I think the js actually uses the IDs of the section, and not the IDs of the component. 

In the design system the IDs of the sections are derived from the component ID - so as long as the component ID is unique across the domain, so will the section IDs. However with the implementation in this repo, a unique ID on the component has no bearing on the section IDs. Repeated accordions on different pages with different IDs will still get the same section IDs. The result is that the 'open' status of each section will be incorrectly shared between them.

## Suggested solution

Change the section IDs to be derived based on the component ID, where set.

**Comment by peteryates** [comment]
I believe #410 resolves this in the best way possible. Setting an id on the accordion itself now propagates down to the sections, which should make it easier to enforce uniqueness. If it's still not enough I can take a proper look at inserting sequential numbers too.

**Comment by edwardhorsford** [comment]
Thanks @peteryates!
