### ISSUE TITLE
Table component

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/govuk-components#53]
Tables might be too complicated to implement using components (#18) as they could potentially need two 'layers' of slots - one for rows and one within it for cells. More investigation is needed

* [ ] Is it possible to nest slots? Can we use this technique to build a table?
* [ ] Would a 'simple' table component work as an alternative, pass in a array of arrays or array of hashes (like `CSV`) and it builds a table itself? `= govuk_table(@teachers)`

**Comment by cpjmcquillan** [comment]
My (teaching-vacancies) original implementation of the summary list component took an array of hashes instead of slots and it worked quite well. I'm about to implement a table component that hopefully includes some sorting bells and whistles - will see how it turns out and link to any findings in here!

**Comment by peteryates** [comment]
Did you make any progress on your table component @cpjmcquillan?

**Comment by cpjmcquillan** [comment]
> Did you make any progress on your table component @cpjmcquillan?

Only just seen this! Eventually we moved away from tables completely since they're not great on smaller screens

**Comment by peteryates** [comment]
Ah, I had a first go at them in #100 but realised my approach was flawed.

Agree on them being annoying on mobile, you know it's bad when even `psql` handles smaller screens better 😞

**Comment by cpjmcquillan** [comment]
> Ah, I had a first go at them in #100 but realised my approach was flawed.
> 
> Agree on them being annoying on mobile, you know it's bad when even `psql` handles smaller screens better 😞

On our service we've started using a concept of cards (which work really nicely on smaller screens). Maybe they'll make their way into the design system one day 🙏
