### ISSUE TITLE
Is the dependency on slim-rails really necessary?

### ISSUE THREAD

**Issue by aliuk2012** [DFE-Digital/govuk-components#56]
This evening I installed this gem and noticed that as part of the installation it added `slim-rails` gem to my Gemfile.lock 

I had a look at the components markup files and none of them use slim so shouldn't [this line](https://github.com/DFE-Digital/govuk-components/blob/master/govuk-components.gemspec#L29) be a dev dependency rather than an actual dependency.

**Comment by peteryates** [comment]
Good call, it's a remnant from the initial commit when I envisioned a guide/demo written in Slim instead of ERB!
