### ISSUE TITLE
NameError: uninitialized constant GovukComponentsHelper

### ISSUE THREAD

**Issue by aliuk2012** [DFE-Digital/govuk-components#58]
I've been trying to add govuk-components to another rails service and came across this issue while trying to deploy the app to production. Everything seems to work and run correctly in development. I'm not sure if perhaps its a config setting in the rails app that is making the server fail when it starts up.

https://github.com/DFE-Digital/get-help-with-tech/pull/466#issuecomment-692632722

**Comment by peteryates** [comment]
Interesting. I can recreate locally by changing `config.load_defaults` from `5.2` and `6.0` as you say in the referenced ticket.

It would appear that between the two versions of Rails, something has changed in the way helpers are loaded. There's more info [here](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#configure-framework-defaults), I'll have a closer look over the next day or two.

**Comment by peteryates** [comment]
Scratch the above, the helper module is called `GovukComponentHelper` (singular) and the file is `govuk_components_helper.rb` (plural), that's _probably_ the cause. I'll fix it tomorrow.

**Comment by aliuk2012** [comment]
I was wondering if it was because of the filename here https://github.com/DFE-Digital/govuk-components/blob/master/app/helpers/govuk_component**s**_helper.rb  but inside the file the module is GovukComponentHelper
