### ISSUE TITLE
'govuk_link_to': govuk-link class not applied correctly when path parameter is a hash

### ISSUE THREAD

**Issue by benilovj** [DFE-Digital/govuk-components#66]
This is a valid invocation of `link_to`:

```ruby
<%= link_to 'abc', param1: 'a', param2: 'b' %>
```
which generates:
```
<a href="/?param1=a&param2=b">abc</a>
```
---

However, calling
```ruby
<%= govuk_link_to 'abc', param1: 'a', param2: 'b' %>
```
unexpectedly generates 
```
<a href="/?class=govuk-link&param1=a&param2=b">abc</a>
```
instead of
```
<a class="govuk-class" href="/?param1=a&param2=b">abc</a>
```

(arose in https://github.com/DFE-Digital/get-help-with-tech/pull/611)

**Comment by peteryates** [comment]
Strange. I'd expect that for `govuk_link_to 'abc', { param1: 'a', param2: 'b' }` the hash would end up in `args` in the [govuk_link_to](https://github.com/DFE-Digital/govuk-components/blob/master/app/helpers/govuk_link_helper.rb) helper but they end up in kwargs, so are merged with the default `govuk-link` class.

Any thoughts on a better approach that still allows custom classes to be added to the default one?

**Comment by benilovj** [comment]
> Any thoughts on a better approach that still allows custom classes to be added to the default one?

Mmm, no, apart from something very hacky like an explicit if statement checking for a hash...

@tijmenb any ideas?

**Comment by peteryates** [comment]
For what it's worth, I just retested what I did earlier using the dummy app rather than specs and this gives you the result you're after:

```erb
<%= govuk_link_to 'abc', { param1: 'a', param2: 'b' } %>
```

Not wrapping the query params in braces makes them end up in `kwargs` rather than `args`.

**Comment by peteryates** [comment]
@benilovj - is providing the extra args in a hash a suitable fix/workaround here?

**Comment by peteryates** [comment]
I'm closing this for the time being, I think the answer above covers why the behaviour occurs and how to avoid it. Agree it's not ideal, happy to revisit if it proves to remain a problem.
