### ISSUE TITLE
Notification banner component

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/govuk-components#70]
The [notification banner](https://design-system.service.gov.uk/components/notification-banner/) component was added to the design system after the scope of this gem was originally agreed. Is it a reasonable candidate for inclusion?

**Comment by peteryates** [comment]
It is absolutely. It'll be in the next release.

**Comment by peteryates** [comment]
I've been thinking over how this might look and think that doing something like this _feels_ sensible:

```erb
<%= render GovukNotificationBanner.new(
  title: "Important",
  heading: "You have 7 days left to send your application",
  link_text: "View application."
  link_target: "/applications/12345"
) %>
```

Additionally, taking a `success` flag to make it green and a block so additional content can be placed beneath the heading if required.

Did I miss anything?

**Comment by frankieroberto** [comment]
@peteryates I don't think it makes sense to split out the heading from the link text and link target, as sometimes you may have multiple links, or other unanticipated content (eg two paragraphs?). Even in the simple example given, the full stop after "View application" should not be part of the link text:

<img width="717" alt="Screenshot 2020-12-01 at 21 11 45" src="https://user-images.githubusercontent.com/30665/100797329-d9edd000-3419-11eb-9b1a-1324d8ede1e3.png">

It might be better to more closely align with the Nunjucks macro options, and having something like:

```ruby
<%= render GovukComponent::NotificationBanner.new(
  title: "Important",
  html: "You have 7 days left to send your application. <a href=\"/applications/12345\">View application</a>."
) %>
```

(There are other macro options we could also support, such as `titleHeadingLevel`, `titleId`, `disableAutoFocus`, `classes` and `attributes`)

**Comment by peteryates** [comment]
@frankieroberto I'm afraid I didn't see your comment until I'd pushed my first crack at it. I built in `classes` and `attributes` but definitely agree that `titleHeadingLevel`, `titleId` and `disableAutoFocus` make sense too. Will address fully in #71

**Comment by peteryates** [comment]
I've kept the `link_text` and `link_target` behaviour for the time being. It is my understanding that links inside the component headings need to have the class `govuk-notification-banner__link` which is a burden for the developer to remember every time they add a link or pass in a `link_to`.

**Comment by paulrobertlloyd** [comment]
Would it be possible to create this banner with this component (i.e. with the unlinked full stop)? https://apply-beta-prototype.herokuapp.com/dashboard/12345/ended-without-success (`apply`/`bat`)

**Comment by peteryates** [comment]
@paulrobertlloyd Yeah, [the associated PR](#71) has a screenshot of the docs with an example call and output.

**Comment by paulrobertlloyd** [comment]
@peteryates Perfect, thanks!
