### ISSUE TITLE
GovukComponent::NotificationBanner cannot be rendered

### ISSUE THREAD

**Issue by asmega** [DFE-Digital/govuk-components#76]
Morning, I've just tried to use the `GovukComponent::NotificationBanner` and does not render. The component has the following implementation

```
  def render?
    headings.any?
  end
```

To add a heading one would use `add_heading` but the component is missing 

```
wrap_slot :heading
```

where `wrap_slot`

```
  def self.wrap_slot(name)
    define_method(%(add_#{name})) do |*args, **kwargs, &block|
      self.slot(name, *args, **kwargs, &block)
    end
  end
```

Is there an alternative way to add headings to this component? Or can `wrap_slot` be added to the component?

**Comment by peteryates** [comment]
Ugh my bad. I'm going to remove this wrap_slot thing completely 🤦🏽‍♂️
